name: Atualizar cursos

on:
  schedule:
    - cron:  "0 3 * * *"
  workflow_dispatch:

jobs:
  atualizar:
    name: Atualizar cursos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::dplyr
            any::tidyr
            any::forcats
            any::stringr
            any::purrr
            any::googlesheets4
            any::glue
      - name: Run script
        run: |
          Rscript R/atualizar_portfolio.R
      - name: Commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . || echo "No changes to commit"
          git commit -m 'updating matches' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
